name: Build
on: [push, pull_request]

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          persist-credentials: false
      - run: cmake .
      - run: cmake --build .
      - run: ctest --output-on-failure

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          persist-credentials: false
      - run: cmake .
      - run: cmake --build .
      - run: ctest --output-on-failure

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
        with:
          persist-credentials: false
      - run: mkdir build && cd build
      - run: cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/android.cmake -DSJPEG_ANDROID_NDK_PATH=$ANDROID_NDK_LATEST_HOME
        working-directory: build
      - run: cmake --build .
        working-directory: build
